cache:
  type: redis
  redis:
    address: "localhost:6379"
    db: 0
    password: ""
    ttl_seconds: 60

event_broker:
  type: kafka
  kafka:
    brokers:
      - "localhost:9092"
    group_id: "goro-group"
    topics:
      - "cache0"
      - "cache1"
    reader:
      min_bytes: 10240
      max_bytes: 10485760
      max_wait_ms: 1000
      queue_capacity: 100


invalidation:
  strategy: versioned-key
  versioned:
    delimiter: ":v"
    default_version: 1